### ISSUE TITLE
Unable to Download Required Resources for Reader Evaluation

### ISSUE THREAD

**Issue by deokhk** [Mayer123/UDT-QA#1]
Hi there!

First of all, I would like to express my appreciation for open-sourcing your work. 

I'm reaching out because I encountered an issue while attempting to perform the reader evaluation as described in the project's ReadMe. Unfortunately, **I've been unable to download the necessary resources needed for this evaluation. It appears that public access to these resources is currently restricted.**

**Command**
```
python download_data.py --resource cos.model.reader.ott --output_dir downloaded
```
**Error stack**

```
Requested resource from %s https://msrdeeplearning.blob.core.windows.net/udq-qa/COS/models/ott_fie_checkpoint_best.pt
Download root_dir %s downloaded
File to be downloaded as %s /home1/deokhk_1/research/UDT-QA/downloaded/downloads/cos/model/reader/ott/ott_fie_checkpoint_best.pt
Traceback (most recent call last):
  File "download_data.py", line 337, in <module>
    main()
  File "download_data.py", line 330, in main
    download(args.resource, args.output_dir)
  File "download_data.py", line 305, in download
    local_file = download_resource(
  File "download_data.py", line 283, in download_resource
    wget.download(link, out=local_file)
  File "/home1/deokhk_1/anaconda3/envs/COS/lib/python3.8/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/home1/deokhk_1/anaconda3/envs/COS/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home1/deokhk_1/anaconda3/envs/COS/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home1/deokhk_1/anaconda3/envs/COS/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home1/deokhk_1/anaconda3/envs/COS/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home1/deokhk_1/anaconda3/envs/COS/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home1/deokhk_1/anaconda3/envs/COS/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home1/deokhk_1/anaconda3/envs/COS/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account.
```
I kindly request your assistance in making the required resources accessible to the public. 

Thank you!

**Comment by MMenonJ** [comment]
Hello,

I was also facing the same issue here. 

Also, I would like to comment that it appears that there are three commas missing in the download_data.py file. 
It would be in the end of the lines: 253, 258 and 264.

I would like to add that I appreciate for your and your team's work, and for making all the codes and data public!

**Comment by Mayer123** [comment]
Thanks for bringing up the issue! 
We have updated the permission on the resources and you should be able to download it now. Let me know if you're still facing any problems.

**Comment by deokhk** [comment]
Thank you for updating the permission. Everything works well!

**Comment by campuslifeceo** [comment]
> Thank you for updating the permission. Everything works well!

Hi there, 
The same issue occurs to me at this moment. I wonder if you could share the data & model.
Regards

**Comment by Tot-ziens** [comment]
> Thanks for bringing up the issue! We have updated the permission on the resources and you should be able to download it now. Let me know if you're still facing any problems.

Great Work,but I have encountered the same error. Could you make resources accessible to the public again?
Best regards

**Comment by Mayer123** [comment]
> > Thanks for bringing up the issue! We have updated the permission on the resources and you should be able to download it now. Let me know if you're still facing any problems.
> 
> Great Work,but I have encountered the same error. Could you make resources accessible to the public again? Best regards

We have migrated most of our data and models to Huggingface, could you please check download_data_hf.py to see if the resources you need are already there? If not, let me know and I will move them to HF asap.

**Comment by Tot-ziens** [comment]
> > > Thanks for bringing up the issue! We have updated the permission on the resources and you should be able to download it now. Let me know if you're still facing any problems.
> > 
> > 
> > Great Work,but I have encountered the same error. Could you make resources accessible to the public again? Best regards
> 
> We have migrated most of our data and models to Huggingface, could you please check download_data_hf.py to see if the resources you need are already there? If not, let me know and I will move them to HF asap.

Tks a lot! I find these data and models on Huggingface.
