### ISSUE TITLE
Public access is not permitted on this storage account..

### ISSUE THREAD

**Issue by campuslifeceo** [Mayer123/UDT-QA#2]
wget https://msrdeeplearning.blob.core.windows.net/udq-qa/data/tables/all_raw_table_chunks_for_index.json

**Comment by Mayer123** [comment]
Hello, we just updated the permission to download data. It should work now.

**Comment by campuslifeceo** [comment]
yeah It works . Thank you so much

**Comment by jaeyoung-l** [comment]
@Mayer123 Hello, Kaixin! It seems that the issue is recurring. I'm getting the same message (409 Public access is not permitted on this storage account.) Could you please check it out?

**Comment by Mayer123** [comment]
@given131 We have moved some of the data and models to HuggingFace for ease of access, please see our README page for instructions to download the data. If the data or models that you need have not been migrated, please let me know and I will prioritize moving those.

**Comment by jaeyoung-l** [comment]
@Mayer123
Thank you for your help, Kaxin! Could you help me with [the knowledge sources in UDT-QA](https://github.com/Mayer123/UDT-QA#knowledge-sources), more specifically, raw and verbalized tables (from Wikipedia) and knowledge bases?

<img width="568" alt="image" src="https://github.com/Mayer123/UDT-QA/assets/35989106/69778be2-ee4c-407d-8d02-190955046221">

**Comment by lifeng7777** [comment]
@Mayer123 
Can you also upload the models and data of CORE to HF? I'm encountering an issue with download_data.py:
HTTP Error 409: Public access is not permitted on this storage account.
However, I also couldn't find the CORE models and data on HF. Could you please take a look and assist? Thank you!

**Comment by Mayer123** [comment]
@lifeng7777  I just migrated CORE data and models to HF.

**Comment by lifeng7777** [comment]
> 

Thank you!

**Comment by NLPerWS** [comment]
could you migrated UDT-QA data and models to HF except Knowledge Source data, include: trained verbalizer model，Retriever data and models，thank you very much!
![Uploading 截屏2024-05-21 16.36.17.png…]()

**Comment by NLPerWS** [comment]
could you migrated UDT-QA data and models to HF except Knowledge Source data, include: trained verbalizer model，Retriever data and models，thank you very much!
<img width="234" alt="截屏2024-05-21 16 36 17" src="https://github.com/Mayer123/UDT-QA/assets/114089542/867aa771-fb0c-4624-ac99-266a4d37765c">

**Comment by NLPerWS** [comment]
could you migrat UDT-QA data and models to HF except Knowledge Source data, include: trained verbalizer model，Retriever data and models，thank you very much!
<img width="234" alt="截屏2024-05-21 16 36 17" src="https://github.com/Mayer123/UDT-QA/assets/114089542/e31f8c99-7e2c-4fe0-af39-8bda1f416bcf">
