### ISSUE TITLE
what is  the ott_expanded_train_iter2 dataset in COS training script

### ISSUE THREAD

**Issue by campuslifeceo** [Mayer123/UDT-QA#3]
I don't find any dataset named ott_expanded_train_iter2 anywhere, is it some refined dataset?

python -m torch.distributed.launch --nproc_per_node=16 python train_dense_encoder_COS.py train=biencoder_nq  train_datasets=[hotpot_train_single,hotpot_train_expanded,hotpot_question_link_train,hotpot_link_train,hotpot_train_rerank,ott_single_train,**ott_expanded_train_iter2**,ott_link_train,ott_rerank_train,NQ_train,NQ_train_table,NQ_train_rerank,NQ_train_table_rerank] dev_datasets=[hotpot_dev_single,hotpot_dev_expanded,hotpot_question_link_dev,hotpot_link_dev,hotpot_dev_rerank] val_av_rank_start_epoch=35 output_dir=/output/dir train.batch_size=12 global_loss_buf_sz=1184000 train.val_av_rank_max_qs=20000 train.warmup_steps=8000 encoder.pretrained_file=/path/to/cos_pretrained_4_experts.ckpt checkpoint_file_name=dpr_biencoder encoder.use_moe=True encoder.num_expert=6 encoder.moe_type=mod2:attn train.use_layer_lr=False train.learning_rate=2e-5 encoder.encoder_model_type=hf_cos

**Comment by Mayer123** [comment]
Sorry for the confusion, it should be ott_expanded_train instead.

**Comment by campuslifeceo** [comment]
Thank you for your reply
