### ISSUE TITLE
 Access Issue with Data Download from Storage Account

### ISSUE THREAD

**Issue by leejiwon1125** [Mayer123/UDT-QA#5]
I encountered an issue while attempting to download the data using the provided download_data.py script. It appears that there is an error associated with accessing the following URL: https://msrdeeplearning.blob.core.windows.net/.

The error message displayed is as follows:
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:e068a9cd-801e-0012-508f-d1d7ed000000 Time:2023-08-18T04:53:00.0657459Z</Message>
</Error>

If this situation is intentional, I would appreciate your guidance on when I might be able to gain access to the data.

Thank you for your assistance.

**Comment by jaeyoung-l** [comment]
@leejiwon1125 Kaixin is finding the way out - migrating to huggingface!  https://github.com/Mayer123/UDT-QA/issues/2

**Comment by Mayer123** [comment]
@given131 @leejiwon1125 The knowledge sources of UDT-QA are just migrated! You can use download_data_hf.py to download the data.

**Comment by leejiwon1125** [comment]
I appreciate all the guidance you provided :)

**Comment by jaeyoung-l** [comment]
Thank you for your help, Kaixin!
