### ISSUE TITLE
Questions Regarding UDT-QA Knowledge Base 

### ISSUE THREAD

**Issue by jaeyoung-l** [Mayer123/UDT-QA#6]
Hello Kaixin! 
I have a question on the dataset you have provided, the KB dataset of UDT-QA(https://huggingface.co/kaixinm/UDT-QA/blob/main/knowledge_sources/WD_graphs_V.zip)

1.  One of the files included in the zip file,  `grouped_WD_graphs.jsonl`. there are some relations of which the length is four.
Following is the example. 
```
{
   "triples":[
      [
         "The Simpsons",
         "award received",
         "Primetime Emmy Award for Outstanding Animated Program"
      ],
      // four elements from below
      [
         "The Simpsons",
         "Primetime Emmy Award for Outstanding Animated Program",
         "winner",
         "Marc Wilmore"
      ],
      [
         "The Simpsons",
         "Primetime Emmy Award for Outstanding Animated Program",
         "winner",
         "Ken Keeler"
      ],
   ]
}
```

In this case, what does each element of four-length relations mean? The 3rd and the 4th one would be relation and target respectively, but I cannot tell the first two.

2. How did you select the knowledge base in WikiData? In the original source, it seems that there are really many knowledge sources (https://www.wikidata.org/wiki/Wikidata:Database_download). I found that the size of the entire wikidata JSON file is 120GB. So, I thought you extracted from the original Wikidata, not using the entire source. How did you filter the data? Can you tell me what part of Wikidata you used?

**Comment by Mayer123** [comment]
For all of our WikiData-related experiments, we used the KELM corpus released by previous work (https://github.com/google-research-datasets/KELM-corpus) and we only did some reformatting. For the triples with four elements, I believe this structure is used to express more complex relations in Wikidata, and we just joined the two elements in the middle and used it as the relation.
